// src/constants/constants.js
import Tech_img from "../assets/blog/1.jpg";
import cloud_img from "../assets/blog/2.png";
import web_img from "../assets/blog/3.jpg";
import security_img from "../assets/blog/4.jpg";
import random_img1 from "../assets/blog/1.jpg"; // Reused image
import random_img2 from "../assets/blog/2.png"; // Reused image
import random_img3 from "../assets/blog/3.jpg"; // Reused image
import random_img4 from "../assets/blog/4.jpg"; // Reused image
import random_img5 from "../assets/blog/5.jpg"; // Reused image
import random_img6 from "../assets/blog/6.jpg"; // Reused image
import random_img7 from "../assets/blog/1.jpg"; // Reused image
import random_img8 from "../assets/blog/2.png"; // Reused image
import random_img9 from "../assets/blog/3.jpg"; // Reused image
import random_img10 from "../assets/blog/4.jpg"; // Reused image

export const BLOG_CARDS = [
  {
    id: 1,
    author: "Kasun Chiwantha",
    subtitle: "Software Engineer / System Admin",
    category: "Technology",
    blogtitle: "Exploring the Latest Tech Trends",
    intro: `Discover the latest trends in technology, from AI advancements to software innovations. Stay ahead with insights on digital tools, coding practices, and tech solutions that shape the future of industries.`,
    image: Tech_img,
  },
  {
    id: 2,
    author: "Amaya Fernando",
    subtitle: "Cloud Solutions Architect",
    category: "Cloud Computing",
    blogtitle: "Future of Cloud Computing",
    intro: `Explore the future of cloud computing, including hybrid models, serverless architectures, and scaling applications efficiently. Learn how to optimize cloud resources and improve infrastructure performance.`,
    image: cloud_img,
  },
  {
    id: 3,
    author: "Ravindu Perera",
    subtitle: "Full Stack Developer",
    category: "Web Development",
    blogtitle: "Mastering Modern Web Development",
    intro: `Master modern web development with in-depth guides on front-end frameworks, back-end technologies, and best practices for building responsive applications using the latest tech stacks.`,
    image: web_img,
  },
  {
    id: 4,
    author: "Nimasha Jayasinghe",
    subtitle: "Cybersecurity Specialist",
    category: "Cybersecurity",
    blogtitle: "Cybersecurity Trends and Strategies",
    intro: `Stay updated on cybersecurity trends, data protection strategies, and how to defend against cyber threats. Learn essential tools and techniques to secure networks and data effectively.`,
    image: security_img,
  },
  {
    id: 5,
    author: "Dilshan Abeysekera",
    subtitle: "Data Scientist",
    category: "Data Science",
    blogtitle: "Harnessing Big Data",
    intro: `Unlock the power of big data with cutting-edge techniques in data analysis, machine learning, and predictive modeling. Learn how data science is transforming industries and decision-making.`,
    image: random_img1,
  },
  {
    id: 6,
    author: "Mihiri Senanayake",
    subtitle: "AI Engineer",
    category: "Artificial Intelligence",
    blogtitle: "Advancements in Artificial Intelligence",
    intro: `Delve into artificial intelligence advancements, including neural networks, natural language processing, and computer vision. Understand how AI is shaping automation and enhancing innovation.`,
    image: random_img2,
  },
  {
    id: 7,
    author: "Janith Weerasinghe",
    subtitle: "Blockchain Developer",
    category: "Blockchain Technology",
    blogtitle: "The Future of Blockchain Technology",
    intro: `Learn about blockchain technology, decentralized applications, and the future of cryptocurrencies. Explore how blockchain is revolutionizing finance, supply chains, and various industries.`,
    image: random_img3,
  },
  {
    id: 8,
    author: "Tharindu Kariyawasam",
    subtitle: "DevOps Engineer",
    category: "DevOps",
    blogtitle: "Best Practices in DevOps",
    intro: `Discover the best practices in DevOps, including CI/CD pipelines, containerization, and automation. Learn how to bridge the gap between development and operations for faster, reliable releases.`,
    image: random_img4,
  },
  {
    id: 9,
    author: "Anjali Dias",
    subtitle: "Mobile App Developer",
    category: "Mobile Development",
    blogtitle: "Building Engaging Mobile Apps",
    intro: `Stay ahead in mobile development with insights on building cross-platform apps, user-friendly designs, and performance optimization. Learn how to develop engaging apps for iOS and Android.`,
    image: random_img5,
  },
  {
    id: 10,
    author: "Kasun Chiwantha",
    subtitle: "Software Engineer / System Admin",
    category: "Technology",
    blogtitle: "The Role of AI in Software Development",
    intro: `Explore how AI tools are transforming software development practices, enhancing productivity, and streamlining workflows.`,
    image: random_img6,
  },
  {
    id: 11,
    author: "Amaya Fernando",
    subtitle: "Cloud Solutions Architect",
    category: "Cloud Computing",
    blogtitle: "Cloud Security Best Practices",
    intro: `Understand the key security practices necessary for safeguarding cloud environments against evolving threats.`,
    image: random_img1,
  },
  {
    id: 12,
    author: "Ravindu Perera",
    subtitle: "Full Stack Developer",
    category: "Web Development",
    blogtitle: "Responsive Web Design Techniques",
    intro: `Learn effective techniques for creating responsive designs that adapt to various screen sizes and devices.`,
    image: random_img2,
  },
  {
    id: 13,
    author: "Nimasha Jayasinghe",
    subtitle: "Cybersecurity Specialist",
    category: "Cybersecurity",
    blogtitle: "Data Breaches: Prevention and Response",
    intro: `Explore strategies for preventing data breaches and effective response measures to take when incidents occur.`,
    image: random_img3,
  },
  {
    id: 14,
    author: "Dilshan Abeysekera",
    subtitle: "Data Scientist",
    category: "Data Science",
    blogtitle: "Predictive Analytics in Business",
    intro: `Discover how predictive analytics can be leveraged to improve business decisions and enhance customer experiences.`,
    image: random_img4,
  },
  {
    id: 15,
    author: "Mihiri Senanayake",
    subtitle: "AI Engineer",
    category: "Artificial Intelligence",
    blogtitle: "Ethics in AI Development",
    intro: `Delve into the ethical considerations of AI development and the importance of responsible AI practices.`,
    image: random_img5,
  },
  {
    id: 16,
    author: "Janith Weerasinghe",
    subtitle: "Blockchain Developer",
    category: "Blockchain Technology",
    blogtitle: "Smart Contracts: A Beginner's Guide",
    intro: `Get an introduction to smart contracts, their functionality, and their applications across various sectors.`,
    image: random_img6,
  },
  {
    id: 17,
    author: "Tharindu Kariyawasam",
    subtitle: "DevOps Engineer",
    category: "DevOps",
    blogtitle: "Automating Deployment with CI/CD",
    intro: `Learn how Continuous Integration and Continuous Deployment (CI/CD) can streamline your deployment process.`,
    image: random_img7,
  },
  {
    id: 18,
    author: "Anjali Dias",
    subtitle: "Mobile App Developer",
    category: "Mobile Development",
    blogtitle: "User Experience in Mobile Apps",
    intro: `Understand the principles of user experience (UX) design for mobile applications and how to implement them.`,
    image: random_img8,
  },
  {
    id: 19,
    author: "Kasun Chiwantha",
    subtitle: "Software Engineer / System Admin",
    category: "Technology",
    blogtitle: "Tech Innovations That Will Shape 2025",
    intro: `Explore the technologies expected to revolutionize industries by 2025, from quantum computing to 5G.`,
    image: random_img9,
  },
  {
    id: 20,
    author: "Amaya Fernando",
    subtitle: "Cloud Solutions Architect",
    category: "Cloud Computing",
    blogtitle: "Introduction to Cloud Native Architecture",
    intro: `Learn the principles of cloud-native architecture and how it supports agile software development practices.`,
    image: random_img10,
  },
  {
    id: 21,
    author: "Ravindu Perera",
    subtitle: "Full Stack Developer",
    category: "Web Development",
    blogtitle: "Web Accessibility: Importance and Techniques",
    intro: `Discover why web accessibility is crucial and the techniques you can use to make your websites accessible to all users.`,
    image: random_img1,
  },
  {
    id: 22,
    author: "Nimasha Jayasinghe",
    subtitle: "Cybersecurity Specialist",
    category: "Cybersecurity",
    blogtitle: "The Importance of Security Awareness Training",
    intro: `Explore the critical role of security awareness training in mitigating human error-related security incidents.`,
    image: random_img2,
  },
  {
    id: 23,
    author: "Dilshan Abeysekera",
    subtitle: "Data Scientist",
    category: "Data Science",
    blogtitle: "Data Visualization: Techniques and Tools",
    intro: `Learn how to effectively visualize data using various tools and techniques to communicate insights clearly.`,
    image: random_img3,
  },
  {
    id: 24,
    author: "Mihiri Senanayake",
    subtitle: "AI Engineer",
    category: "Artificial Intelligence",
    blogtitle: "Machine Learning Algorithms Explained",
    intro: `Gain an understanding of various machine learning algorithms and how they are applied in real-world scenarios.`,
    image: random_img4,
  },
  {
    id: 25,
    author: "Janith Weerasinghe",
    subtitle: "Blockchain Developer",
    category: "Blockchain Technology",
    blogtitle: "Decentralized Finance: An Overview",
    intro: `Explore the world of decentralized finance (DeFi) and its implications for traditional financial systems.`,
    image: random_img5,
  },
  {
    id: 26,
    author: "Tharindu Kariyawasam",
    subtitle: "DevOps Engineer",
    category: "DevOps",
    blogtitle: "Monitoring and Logging Best Practices",
    intro: `Learn about best practices for monitoring applications and logging to ensure performance and reliability.`,
    image: random_img6,
  },
  {
    id: 27,
    author: "Anjali Dias",
    subtitle: "Mobile App Developer",
    category: "Mobile Development",
    blogtitle: "The Rise of Progressive Web Apps",
    intro: `Understand what Progressive Web Apps (PWAs) are and their benefits for users and developers alike.`,
    image: random_img7,
  },
  {
    id: 28,
    author: "Kasun Chiwantha",
    subtitle: "Software Engineer / System Admin",
    category: "Technology",
    blogtitle: "Understanding Agile Methodologies",
    intro: `Learn about agile methodologies and how they can improve project management and software delivery.`,
    image: random_img8,
  },
  {
    id: 29,
    author: "Amaya Fernando",
    subtitle: "Cloud Solutions Architect",
    category: "Cloud Computing",
    blogtitle: "Best Cloud Providers in 2024",
    intro: `Get insights into the best cloud service providers in 2024 and what sets them apart in the industry.`,
    image: random_img9,
  },
  {
    id: 30,
    author: "Ravindu Perera",
    subtitle: "Full Stack Developer",
    category: "Web Development",
    blogtitle: "Frontend Frameworks: React vs. Angular",
    intro: `Compare React and Angular to find out which framework suits your web development needs best.`,
    image: random_img10,
  },
  {
    id: 31,
    author: "Nimasha Jayasinghe",
    subtitle: "Cybersecurity Specialist",
    category: "Cybersecurity",
    blogtitle: "Incident Response Planning",
    intro: `Explore how to create an effective incident response plan to prepare for cybersecurity incidents.`,
    image: random_img1,
  },
  {
    id: 32,
    author: "Dilshan Abeysekera",
    subtitle: "Data Scientist",
    category: "Data Science",
    blogtitle: "The Importance of Data Quality",
    intro: `Understand why data quality is crucial for data-driven decision-making and how to maintain it.`,
    image: random_img2,
  },
  {
    id: 33,
    author: "Mihiri Senanayake",
    subtitle: "AI Engineer",
    category: "Artificial Intelligence",
    blogtitle: "AI in Healthcare: Transforming Patient Care",
    intro: `Explore how AI is revolutionizing healthcare by improving diagnostics and personalizing patient care.`,
    image: random_img3,
  },
  {
    id: 34,
    author: "Janith Weerasinghe",
    subtitle: "Blockchain Developer",
    category: "Blockchain Technology",
    blogtitle: "Blockchain and Supply Chain Management",
    intro: `Learn how blockchain technology is enhancing transparency and efficiency in supply chain management.`,
    image: random_img4,
  },
  {
    id: 35,
    author: "Tharindu Kariyawasam",
    subtitle: "DevOps Engineer",
    category: "DevOps",
    blogtitle: "Infrastructure as Code: An Introduction",
    intro: `Discover the fundamentals of Infrastructure as Code (IaC) and its benefits in modern software development.`,
    image: random_img5,
  },
  {
    id: 36,
    author: "Anjali Dias",
    subtitle: "Mobile App Developer",
    category: "Mobile Development",
    blogtitle: "App Monetization Strategies",
    intro: `Learn effective strategies for monetizing mobile applications and maximizing revenue opportunities.`,
    image: random_img6,
  },
  {
    id: 37,
    author: "Kasun Chiwantha",
    subtitle: "Software Engineer / System Admin",
    category: "Technology",
    blogtitle: "The Impact of 5G Technology",
    intro: `Understand how 5G technology is transforming connectivity and enabling innovations across industries.`,
    image: random_img7,
  },
  {
    id: 38,
    author: "Amaya Fernando",
    subtitle: "Cloud Solutions Architect",
    category: "Cloud Computing",
    blogtitle: "Containerization: Docker and Kubernetes",
    intro: `Explore containerization technologies like Docker and Kubernetes and how they improve application deployment.`,
    image: random_img8,
  },
  {
    id: 39,
    author: "Ravindu Perera",
    subtitle: "Full Stack Developer",
    category: "Web Development",
    blogtitle: "SEO Best Practices for 2024",
    intro: `Stay updated on the best SEO practices for 2024 to improve website visibility and organic traffic.`,
    image: random_img9,
  },
  {
    id: 40,
    author: "Nimasha Jayasinghe",
    subtitle: "Cybersecurity Specialist",
    category: "Cybersecurity",
    blogtitle: "Securing Remote Work Environments",
    intro: `Learn how to secure remote work environments to protect against evolving cyber threats and vulnerabilities.`,
    image: random_img10,
  },
];
